export const USER_PERMISSION_GROUPS = [
  { key: "home", label: "Home", actions: ["ventasview", "ventasviewall", "posventaview", "posventaviewall"] },
  { key: "usuarios", label: "Usuarios", actions: ["view", "create", "edit", "delete"] },
  { key: "clientes", label: "Clientes", actions: ["view", "viewall", "create", "edit", "delete", "vehicles", "import", "export", "vehicles_import", "vehicles_export", "maintenance_import", "maintenance_export"] },
  { key: "proveedores", label: "Proveedores", actions: ["view", "create", "edit", "delete"] },
  { key: "marcas", label: "Marcas", actions: ["view", "create", "edit", "delete"] },
  { key: "modelos", label: "Modelos", actions: ["view", "create", "edit", "delete"] },
  { key: "clases", label: "Clases de Vehiculos", actions: ["view", "create", "edit", "delete"] },
  { key: "algoritmo_visita", label: "F. de mantenimiento", actions: ["view", "create", "edit", "delete"] },
  { key: "inventario", label: "Inventario", actions: ["view", "create", "edit", "delete"] },
  { key: "ubicacion_inventario", label: "Ubicacion Inventario", actions: ["view", "create", "edit", "delete", "import"] },
  { key: "combomantenimiento", label: "Mantenimientos", actions: ["view", "create", "edit", "delete"] },
  { key: "submantenimiento", label: "Submantenimientos", actions: ["view", "create", "edit", "delete"] },
  { key: "configinventario", label: "Config. Inventario", actions: ["view", "create", "edit", "delete"] },
  { key: "config_anaqueles", label: "Config. Anaqueles", actions: ["view", "create", "edit", "delete"] },
  { key: "inventariocarros", label: "Precios de Carros", actions: ["view", "create", "edit", "delete", "import", "export", "history", "history_create", "history_edit", "history_import", "history_export", "pending_purchase"] },
  { key: "catalogoventa", label: "Catalogo Venta", actions: ["view", "create", "edit", "delete", "import", "export"] },
  { key: "accesoriosventa", label: "Accesorios Venta", actions: ["view", "create", "edit", "delete"] },
  { key: "regalosventa", label: "Regalos Venta", actions: ["view", "create", "edit", "delete"] },
  { key: "prospeccion", label: "Auto prospeccion", actions: ["view", "create", "edit", "delete"] },
  { key: "citas", label: "Agenda PostVenta", actions: ["view", "create", "edit", "delete", "viewall"] },
  { key: "oportunidadespv", label: "Oportunidades PosVenta", actions: ["view", "create", "edit", "delete", "viewall", "asignar"] },
  { key: "leadspv", label: "Leads PostVenta", actions: ["view", "create", "edit", "delete", "viewall", "asignar"] },
  { key: "ordenespv", label: "Ordenes PostVenta", actions: ["view", "viewall", "create", "edit", "delete"] },
  { key: "planeador_tallerpv", label: "Planeador Taller PV", actions: ["view", "viewall", "create", "edit", "delete"] },
  { key: "cotizacion", label: "Cotizacion", actions: ["view", "viewall", "create", "edit", "delete", "status"] },
  { key: "cotizacion_ford", label: "Cotizacion Ford", actions: ["view"] },
  { key: "cotizacion_otros", label: "Cotizacion Otros", actions: ["view"] },
  { key: "agenda", label: "Agenda", actions: ["view", "create", "edit", "viewall"] },
  { key: "oportunidades", label: "Oportunidades", actions: ["view", "create", "edit", "delete", "viewall", "asignar"] },
  { key: "leads", label: "Leads", actions: ["view", "create", "edit", "delete", "viewall", "asignar"] },
  { key: "leads_ford", label: "Leads Ford", actions: ["view", "sync", "create", "edit", "manual_import"] },
  { key: "reservas", label: "Reservas Venta", actions: ["view", "viewall", "review", "firm", "edit", "car_data", "send_signature", "observe", "subsanate", "sign"] },
  { key: "configagenda", label: "Config. Ventas", actions: ["view", "create", "edit", "delete"] },
  { key: "configuracion_horas", label: "Config. Horas", actions: ["view", "create", "edit", "delete"] },
  { key: "configuracion_usuario_counts", label: "Conteos Usuarios", actions: ["view", "create", "edit", "delete"] },
  { key: "config_ventas_plantillas", label: "Plantillas Venta", actions: ["view", "create", "edit", "delete"] },
  { key: "configcotizacion", label: "Config. Citas", actions: ["view", "create", "edit", "delete"] },
  { key: "config_posventa_cierres", label: "Config. Cierres PostVenta", actions: ["view", "create", "edit", "delete"] },
  { key: "config_tipos_medida", label: "Config. Tipos Medida", actions: ["view", "create", "edit", "delete"] },
  { key: "reportes", label: "Reportes", actions: ["view"] },
  { key: "notificaciones", label: "Notificaciones", actions: ["send"] },
  { key: "sistema_logistico", label: "Sistema Logistico", actions: ["view"] },
  { key: "puntoventa", label: "Punto de Venta", actions: ["view"] },
  { key: "config_puntoventa", label: "Config. Punto de Venta", actions: ["view", "create", "edit", "delete"] },
  { key: "mensajes", label: "Mensajes", actions: ["view", "create", "edit", "delete"] },
  { key: "configuracion", label: "Configuracion", actions: ["view", "create", "edit", "delete"] },
  { key: "configuracion_centros", label: "Config. Centros", actions: ["view", "create", "edit", "delete"] },
  { key: "configuracion_talleres", label: "Config. Talleres", actions: ["view", "create", "edit", "delete"] },
  { key: "configuracion_mostradores", label: "Config. Mostradores", actions: ["view", "create", "edit", "delete"] },
  { key: "configuracion_motivos_citas", label: "Config. Motivos", actions: ["view", "create", "edit", "delete"] },
  { key: "configuracion_submotivos_citas", label: "Config. Submotivos", actions: ["view", "create", "edit", "delete"] },
  { key: "configuracion_origenes_citas", label: "Config. Origenes", actions: ["view", "create", "edit", "delete"] },
  { key: "configuracion_suborigenes_citas", label: "Config. Suborigenes", actions: ["view", "create", "edit", "delete"] },
  { key: "configuracion_monedas", label: "Config. Monedas", actions: ["view", "create", "edit", "delete"] },
  { key: "configuracion_impuestos", label: "Config. Impuestos", actions: ["view", "create", "edit", "delete"] },
  { key: "configuracion_links", label: "Config. Links", actions: ["view", "create", "edit", "delete"] },
  { key: "configuracion_roles", label: "Config. Roles", actions: ["view", "create"] },
  { key: "configuracion_tarifas_mano_obra", label: "Config. Mano de Obra", actions: ["view", "create", "edit", "delete"] },
  { key: "configuracion_tarifas_panos", label: "Config. Panos", actions: ["view", "create", "edit", "delete"] },
  { key: "configuracion_frecuencia", label: "Config. Frecuencia", actions: ["view", "create", "edit", "delete"] },
];

export const WORK_DAYS = [
  { key: "monday", label: "Lunes" },
  { key: "tuesday", label: "Martes" },
  { key: "wednesday", label: "Miercoles" },
  { key: "thursday", label: "Jueves" },
  { key: "friday", label: "Viernes" },
  { key: "saturday", label: "Sabado" },
  { key: "sunday", label: "Domingo" },
];

export function defaultWorkSchedule() {
  return Object.fromEntries(
    WORK_DAYS.map((day) => [
      day.key,
      { active: ["monday", "tuesday", "wednesday", "thursday", "friday"].includes(day.key), start: "08:00", end: "18:00" },
    ])
  );
}
